export default function () {
  return {
    id: "",
    currency_id: "",
    name: "",
    type: "",
    address: "",
    city: "",
    sector: "",
    country: "",
    phone: "",
    email: "",
    website: "",
    info: "",
    logo: "",
    shares: "",
    taxrate: "",
    currency_name: "",
    currency_symbol: "",
    currency_code: "",
    country_name: "",
    country_region: "",
    country_subregion: "",
    country_latitude: "",
    country_longitude: "",
  };
}
